press_f_to_pay_respects/dndpal/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('simple/', views.simple, name='simple'),
    path('profile/', views.profile, name='profile'),
    path('armors/', views.ArmorListView.as_view(), name='armors'),
    path('armor/<str:pk>', views.ArmorDetailView.as_view(), name='armor-detail'),
    path('equipment/', views.EquipmentListView.as_view(), name='equipment'),
    path('equipment/<str:pk>', views.EquipmentDetailView.as_view(), name='equipment-detail'),
    path('races/', views.RaceListView.as_view(), name='races'),
    path('race/<str:pk>', views.RaceDetailView.as_view(), name='race-detail'),
    path('weapons/', views.WeaponListView.as_view(), name='weapons'),
    path('weapon/<str:pk>', views.WeaponDetailView.as_view(), name='weapon-detail'),
    path('spells/', views.SpellListView.as_view(), name='spells'),
    path('spell/<str:pk>', views.SpellDetailView.as_view(), name='spell-detail'),
    path('classes/', views.CharacterClassListView.as_view(), name='classes'),
    path('class/<str:pk>', views.CharacterClassDetailView.as_view(), name='class-detail'),
    path('alan', views.alan, name='alan'),

    #path('armor/custom_form/', views.custom_armor_form, name='custom-armor-form'), # if for already made shit, arnmor/<uuid:pk>/custom_form/ ?
    path('armor/create/', views.ArmorCreate.as_view(), name='armor_create'),
    path('armor/<str:pk>/update/', views.ArmorUpdate.as_view(), name='armor_update'),
    path('armor/<str:pk>/delete/', views.ArmorDelete.as_view(), name='armor_delete'),

#ajax all the ajax
    url(r'^ajax/get_health/(?P<stub>[-\w]+)$', views.get_health, name='get_health'),
	url(r'^ajax/get_skills/(?P<cname>[-\w]+)$', views.get_skills),
	url(r'^ajax/get_spells/(?P<cname>[-\w]+)/(?P<lvl>[-\w]+)/$', views.get_spells),
    url(r'^ajax/get_cantrip/(?P<cname>[-\w]+)/$', views.get_cantrip),
	url(r'^ajax/get_features/(?P<cname>\w+)/(?P<lvl>\w+)/$', views.get_features),
    url(r'^ajax/get_abilites/(?P<cname>\w+)/(?P<lvl>\w+)/$', views.get_abilites),
    url(r'^ajax/test_post/$', views.testing_post),
    url(r'^ajax/get_character/(?P<id>[-\w]+)/$', views.get_character),
]






from django.conf.urls import url


# Niko's pages:
urlpatterns += [
     url(r'^signup/$', views.signup, name='signup'),
    path('guided/', views.guided, name='guided'),
    path('character/create/', views.CharacterCreateForm, name='character_create'),

]


urlpatterns += [
    path('mycharacters/', views.CharacterListView.as_view(), name='my-characters'),
    path('character/<uuid:pk>', views.CharacterDetailView.as_view(), name ='character-detail'),
]

press_f_to_pay_respects/press_f_to_pay_respects/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('dndpal/', include('dndpal.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/dndpal/')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

press_f_to_pay_respects/dndpal/models.py
"""
TO-DO:
Things to ask Alan:
- Implement __str__ representations of the models
- Have Alan change the help text for stuff as appropriate
"""

from django.db import models

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

from django.contrib.auth.models import User

# Create your models here.
import uuid


class Character(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    username = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
    char_name = models.CharField( default = '', max_length = 30, help_text = "Enter a name for your character")
    char_class = models.ForeignKey('CharacterClass', on_delete=models.SET_NULL, null = True)
    race = models.ForeignKey('Race', on_delete=models.SET_NULL, null = True)
    subrace = models.ForeignKey('Subrace', on_delete=models.SET_NULL, null = True)
    level = models.PositiveSmallIntegerField(default = 0, help_text = "Enter the level your character")

    # In tuple: First field is the value that gets saved in the database, Second is the one the human sees
    ALIGNMENT_CHOICES = (
        ('LG', 'Lawful Good'),
        ('NG', 'Neutral Good'),
        ('CG', 'Chaotic Good'),

        ('LN', 'Lawful Neutral'),
        ('NN', 'True Neutral'),
        ('CN', 'Chaotic Neutral'),

        ('LE', 'Lawful Evil'),
        ('NE', 'True Neutral'),
        ('CE', 'Chaotic Evil')
    )

    alignment = models.CharField(max_length = 2, choices = ALIGNMENT_CHOICES, default = 'NN')
    proficiency_list = models.CharField( default = '', max_length = 30, blank=True, help_text = "Enter the list of proficiencies for this character in JSON format.")
    ability_list = models.CharField( default = '', max_length = 1000, blank=True, help_text = "Enter the list of abilities for this character in JSON format.")
    spell_list = models.CharField( default = '', max_length = 1000, blank=True, help_text = "Enter the list of spells for this character in JSON format.")
    gold = models.IntegerField(default=0, help_text="Enter the gold of the character")
    silver = models.IntegerField(default=0, help_text="Enter the gold of the character")
    copper = models.IntegerField(default=0, help_text="Enter the gold of the character")
    exp = models.IntegerField(default=0, help_text="Enter the exp of the character")

    armor = models.ForeignKey('Armor', on_delete=models.SET_NULL, null = True)
    weapon = models.ForeignKey('Weapon', on_delete=models.SET_NULL, null = True)
    items = models.CharField(default = '', max_length = 5000, help_text = "Enter list of inventory items")
    max_hp = models.PositiveSmallIntegerField(default = 1, help_text = "Enter the max hitpoints for your character")
    temp_hp = models.PositiveSmallIntegerField(default = 1, help_text = "Enter the temporary hitpoints for your character")
    cur_hp = models.PositiveSmallIntegerField(default = 1, help_text = "Enter the current hitpoints for your character")
    armor_class = models.PositiveSmallIntegerField(default = 1, help_text = "Enter the armor class for your character")
    init = models.PositiveSmallIntegerField(default = 1, help_text = "Enter the initiative bonus for your character")
    bonus_list = models.CharField( default = '', max_length = 1000, blank=True, help_text = "Enter the list of bonuses for this character in JSON format.")

    strength = models.SmallIntegerField(default= 0, help_text="Enter the strength state for your character.")
    dexterity = models.SmallIntegerField(default= 0, help_text="Enter the dexterity state for your character.")
    constitution = models.SmallIntegerField(default= 0, help_text="Enter the constitution state for your character.")
    intelligence = models.SmallIntegerField(default= 0, help_text="Enter the intelligence state for your character.")
    wisdom = models.SmallIntegerField(default= 0, help_text="Enter the wisdowm state for your character.")
    charisma = models.SmallIntegerField(default= 0, help_text="Enter the charisma state for your character.")

    character_view = models.CharField( default = '', max_length = 30, help_text = "Enter view for character (simple/guided/manual).")






    def __str__(self):
        return self.char_name

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this Character.
        """
        return reverse('character-detail', args=[str(self.name)])

class Race(models.Model):
    name = models.CharField(default = '', primary_key = True, max_length = 100, help_text = "Enter the name of this race")
    description = models.CharField(default = '', max_length = 5000, help_text = "Enter a description of this race (backstory, beliefs, etc.)")
    speed = models.SmallIntegerField(default=0, help_text="Enter the speed for this race")
    # Only applied once at character creation, will use a JS parser (or something) to parse the raw string (format of string is JSON)
    # object and apply the mods to the characters stats
    modifiers = models.CharField(default = '', max_length = 100, help_text = "Enter the stats modifiers in JSON format. Ex: {\"str\": 2, \"dex\": 8}")


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this Race.
        """
        return reverse('race-detail', args=[str(self.name)])

class RaceFeatures(models.Model):
    name = models.CharField(default = '', max_length = 100, help_text = "Enter the name of this race feature")
    race = models.ForeignKey('Race', on_delete=models.CASCADE, null = True)
    description = models.CharField(default= '', max_length = 5000, help_text = "Enter a description of this feature; i.e. what this feature does")
    required_level = models.SmallIntegerField(default= 0, null=True, help_text="Enter the required level for this feature")
    feature_type = models.CharField(default= '', max_length = 5000, help_text = "Enter a note what this feature modifies")

class Subrace(models.Model):
    name = models.CharField(default = '', primary_key = True, max_length = 100, help_text = "Enter the name of the subrace")
    parent_race = models.ForeignKey('Race', on_delete=models.CASCADE, null = True)
    description = models.CharField(default= '', max_length = 5000, help_text = "Enter a description of this sub-race (backstory, beliefs, etc.)")
    modifiers = models.CharField(default = '', max_length = 20, help_text = "Enter the stats modifiers in JSON format. Ex: {\"str\": 2, \"dex\": 8}")
    def __str__(self):
        return self.name


class SubraceFeatures(models.Model):
    subrace = models.ForeignKey('Subrace', on_delete=models.CASCADE, null = True)
    required_level = models.SmallIntegerField(default= 0, null=True, help_text="Enter the required level for this feature")
    sub_feature_name = models.CharField(default = '', max_length = 100, help_text = "Enter the name of this feature")
    #name = models.CharField(default = '', primary_key = True, max_length = 100, help_text = "Enter the name of the subrace")
    description = models.CharField(default= '', max_length = 5000, help_text = "Enter a description for these features")
    feature_type = models.CharField(default= '', max_length = 5000, help_text = "Enter a note what this feature modifies")

class CharacterClass(models.Model):
    name = models.CharField(default = '', primary_key = True, max_length = 100, help_text = "Enter the name of this class")
    descrtiption = models.CharField(default = '', max_length = 1000, help_text = "Enter a description of this class")
    hitpoints = models.PositiveIntegerField(default = 10, help_text = "Enter the hitdie of this class")
    skill_proficiency_limit = models.PositiveSmallIntegerField(default = 5, help_text = "Enter the max amount of skills this class can be proficient in")
    skill_list = models.CharField(default = '', max_length = 300, help_text = "Enter a comma separated skill list. Ex: \"Acrobatics,Intimidation\" \(without the quotations\)")
    armor_prof = models.CharField(default = "", max_length = 10000, help_text = "Enter a comma separated of armor proficiencies list for the class")
    weapon_prof = models.CharField(default = "", max_length = 10000, help_text = "Enter a comma separated of weapon proficiencies list for the class")
    saving_throws = models.CharField(default = "", max_length = 10000, help_text = "Enter a comma separated list of saving throws for the class")
    recommended_gear = models.CharField(default = "", max_length = 10000, help_text = "Enter the names of the recommended gear for this class")


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a detail record for this class.
        """
        return reverse('class-detail', args=[str(self.name)])

class CharacterClassSpellList(models.Model):
    character_class = models.ForeignKey('CharacterClass', on_delete=models.CASCADE, null = True)
    required_level = models.SmallIntegerField(default= 0, null=True, help_text="Enter the required level for this spell")
    ranking = models.SmallIntegerField(default= 0, null=True, help_text="Enter the recommended ranking of this spell relative to the other spells available for this class on a scale from 1-5. 5 being the best and 1 being the worst.")
    spell_list = models.ForeignKey('Spell', on_delete=models.CASCADE)
    ran_note = models.CharField(default = "", max_length = 10000, help_text = "Enter the ranking note for this spell for this class")

class CharacterClassFeatures(models.Model):
    name = models.CharField(default = '', max_length = 100, help_text = "Enter the name of this class feature")
    character_class = models.ForeignKey('CharacterClass', on_delete=models.CASCADE, null = True)
    description = models.CharField(default= '', max_length = 5000, help_text = "Enter a description of this feature; i.e. what this feature does")

press_f_to_pay_respects/dndpal/forms.py
# from django import forms
# from djang.forms import ModelForm
# from .models import Armor

# from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _

# class CustomArmorForm(ModelForm):
# 	class Meta:
# 		model = Armor
# 		fields = '__all__'
# 		labels = { 'name':_('Armor Name'), 'is_stealth':_('Stealth'), }
# 		initial = 

# 	# name = forms.CharField(initial='Armor Name', max_length = 100, help_text = "Enter the name of the armor")
#  #    armor_bonus = forms.SmallIntegerField(help_text="Enter the armor bonus (AC) for this item in pounds.")
#  #    max_dexterity = forms.SmallIntegerField(initial=0, help_text="Enter the maximum amount of bonus AC from dex modifier.")
#  #    is_stealth = forms.BooleanField(help_text="Is the armor not loud?")
#  #    # armor class (light, med, heavy)?
#  #    #Units: Pounds (lbs)
#  #    weight = forms.SmallIntegerField(help_text="Enter the weight for this item in pounds.")
# 	# gold = forms.IntegerField(help_text="Enter the gold-price component for this armor")
# 	# silver = forms.IntegerField(help_text="Enter the silver-price component for this armor")
# 	# copper = forms.IntegerField(help_text="Enter the copper-price component for this armor")
# 	# required_strength = forms.SmallIntegerField(required=False, default= 0, help_text="Enter the required strength to use this armor.")
#  #    required_materials = forms.CharField(default = "", max_length = 10000, help_text = "Enter the required materials to cast this spell in JSON format.")

#     def clean_required_stength(self):
#     	data =  self.cleaned_data['required_strength']
#     	# Check number is not negative
#     	if data < 0:
#     		raise ValidationError(_('Invalid strength requirement; value is negative'))
#     	# Check number is not above 20
#     	if data > 20:
#     		raise ValidationError(_('Invalid strength requirement; value is greater than maximum stength, 20'))

#     	return data

#     def clean_gold(self):
#     	data =  self.cleaned_data['gold']
#     	# Check number is not negative
#     	if data < 0:
#     		raise ValidationError(_('Invalid gold price; cost is negative'))
#     	return data

#     def clean_silver(self):
#     	data =  self.cleaned_data['silver']
#     	# Check number is not negative
#     	if data < 0:
#     		raise ValidationError(_('Invalid silver price; cost is negative'))
#     	return data

#     def clean_copper(self):
#     	data =  self.cleaned_data['copper']
#     	# Check number is not negative
#     	if data < 0:
#     		raise ValidationError(_('Invalid copper price; cost is negative'))
#     	return data


#     def clean_required_materials(self):
#     	pass
#     	# I have no idea how to enforce JSON format


# class Armor(models.Model):
#     def get_absolute_url(self):
#         """
#         Returns the url to access a detail record for this armor.
#         """
#         return reverse('armor-detail', args=[str(self.name)])


from django.forms import ModelForm
from .models import Character

class CharacterForm(ModelForm):
    class Meta:
        model = Character
        fields = ['char_name','char_class','race','subrace']

press_f_to_pay_respects/dndpal/templates/char_list.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<main role="main" class="container">
    <div class="container">

        <div class="row" style="margin-top: 10px">
            <!--Grid column-->
            <div class="col-md-5">

                <h1>Characters</h1>
                <hr>


            </div>

        </div>

        <div class="list-group">
            {% if character_list %}
                {% for c in character_list %}
                    <a href="{% url 'character-detail' c.pk %}" class="list-group-item list-group-item-action flex-column align-items-start"
                       style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px">

                        <table>
                            <col width="20%">
                            <col width="80%">
                            <tbody>
                            <tr>
                                <th>
                                    <div class="avatar">
                                        <img style="width:75%; max-width: 400px;height:auto;"src="{% static 'img/barb-weapon.png' %}"class="rounded-circle img-responsive">
                                    </div>
                                </th>
                                <th scope="row">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1"><b>Name: {{c.char_name}}</b></h5>
                                        <small class="text-muted">LVL {{c.level}}</small>
                                    </div>
                                    <div class="d-flex w-100 justify-content-between" style="align-items: center;">
                                        <p class="mb-1">Race: {{c.race}} <br/> Class: {{c.char_class}}</p>
                                        <button type="button" class="btn btn-flat btn-danger">Delete</button>
                                    </div>
                                </th>
                            </tr>
                            </tbody>
                        </table>
                    </a>
                {% endfor %}
                    <a href="{% url 'character_create' %}" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%;
													  max-width: 400px;
													  height:auto;"
                                     src="{% static 'img/Add.png' %}"
                                     class="rounded-circle img-responsive"
                                >
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Add New</h5>
                                <small class="text-muted"></small>
                            </div>
                            <p class="mb-1"></p>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>
            {% else %}
                <h1>There are no characters.</h1>
                <a href="{% url 'character_create' %}" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%;
													  max-width: 400px;
													  height:auto;"
                                     src="{% static 'img/Add.png' %}"
                                     class="rounded-circle img-responsive"
                                >
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Add New</h5>
                                <small class="text-muted"></small>
                            </div>
                            <p class="mb-1"></p>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>
            {% endif %}
            <!--Grid column-->

        </div>
        <!--Main container-->
    </div>
</main>




{% endblock %}

press_f_to_pay_respects/dndpal/templates/character_form.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
<main role="main" class="container">
  <div class="container ml-5 mt-4">
    <div class="row">
      <div class="col-md-11">
        <div class="card pl-5 pr-4 pb-4">
          <div class="card-header">
            <h2 class="my-4 text-center">Create Character</h2>
          </div>
          <div class="card-body">
            <form method="post" class="mt-3 p-3">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-outline-primary mt-4">Create Character</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

press_f_to_pay_respects/dndpal/templates/character_list_user.html
{% extends "base_generic.html" %}

{% block content %}


<main role="main" class="container">
    <div class="container">

        <div class="row" style="margin-top: 10px">
            <!--Grid column-->
            <div class="col-md-5">

                <h1>Characters</h1>
                <hr>


            </div>

        </div>

        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%; max-width: 400px;height:auto;"src="img/bar.png"class="rounded-circle img-responsive">
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Friar Jarl</h5>
                                <small class="text-muted">LVL 7</small>
                            </div>
                            <div class="d-flex w-100 justify-content-between" style="align-items: center;">
                                <p class="mb-1">Half-Orc Barbarian</p>
                                <button type="button" class="btn btn-flat btn-danger">Delete</button>
                            </div>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>

            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%; max-width: 400px;  height:auto;"   src="img/rouge.png" class="rounded-circle img-responsive">
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Sneacky McSneack face</h5>
                                <small class="text-muted">LVL 1</small>
                            </div>
                            <div class="d-flex w-100 justify-content-between" style="align-items: center;">
                                <p class="mb-1">Human Rouge</p>
                                <button type="button" class="btn btn-flat btn-danger">Delete</button>
                            </div>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>

            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%;max-width: 400px;height:auto;"        src="img/Ranger.png"class="rounded-circle img-responsive">
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Graceuvial Taletreader</h5>
                                <small class="text-muted">LVL 12</small>
                            </div>
                            <div class="d-flex w-100 justify-content-between" style="align-items: center;">
                                <p class=" mb-1">Half-Elf Ranger</p>
                                <button type="button" class="btn btn-flat btn-danger">Delete</button>
                            </div>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>

            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
               style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

                <table>
                    <col width="20%">
                    <col width="80%">
                    <tbody>
                    <tr>
                        <th>
                            <div class="avatar">
                                <img style="width:75%;max-width: 400px;height:auto;"src="img/add.png"class="rounded-circle img-responsive">
                            </div>
                        </th>
                        <th scope="row">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">Add New</h5>
                                <small class="text-muted"></small>
                            </div>
                            <p class="mb-1"></p>
                        </th>
                    </tr>
                    </tbody>
                </table>
            </a>
            <!--Grid column-->

        </div>
        <!--Main container-->
    </div>
</main>
<h1>Characters list test</h1>

{% if character_list %}
<ul>
    <li>
    {% for c in character_list %}

        <a href="{% url 'character-detail' c.pk %}">{{c.char_name}}</a> ({{ c.char_class.name }})

    {% endfor %}

        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
           style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

            <table>
                <col width="20%">
                <col width="80%">
                <tbody>
                <tr>
                    <th>
                        <div class="avatar">
                            <img style="width:75%;max-width: 400px;height:auto;"
                                 src="img/add.png"
                                 class="rounded-circle img-responsive"
                            >
                        </div>
                    </th>
                    <th scope="row">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">Add New</h5>
                            <small class="text-muted"></small>
                        </div>
                        <p class="mb-1"></p>
                    </th>
                </tr>
                </tbody>
            </table>
        </a>

    {% else %}
        <p>There are no characters.</p>

        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start"
       style=" border-radius: 25px;background-color: #DCDCDC; margin-bottom:5px ">

        <table>
            <col width="20%">
            <col width="80%">
            <tbody>
            <tr>
                <th>
                    <div class="avatar">
                        <img style="width:75%;max-width: 400px;height:auto;"
                             src="img/add.png"
                             class="rounded-circle img-responsive"
                        >
                    </div>
                </th>
                <th scope="row">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Add New</h5>
                        <small class="text-muted"></small>
                    </div>
                    <p class="mb-1"></p>
                </th>
            </tr>
            </tbody>
        </table>
    </a>

    {% endif %}
    </li>
</ul>
{% endblock %}

press_f_to_pay_respects/dndpal/templates/material_form_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block title %}<title>Sign Up | DnDPal </title>{% endblock %}
    {% include 'material/includes/material_css.html' %}
    {% include 'material/includes/material_js.html' %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    {% include 'material/includes/material_js.html' %}
    
</head>

<body> 
    {% block body %}
    
    
    
    {% endblock %}
</body>

</html>

press_f_to_pay_respects/dndpal/templates/simple.html
{% extends "base_generic.html" %}

{% block title %}<title>Simple</title>{% endblock %}

{% block content %}

<!--Main layout-->
<main role="main" class="container">

  <h3> Simple STATIC pages here (if we get to it):</h3>
  <p>press_f_to_pay_respects/dndpal/templates/simple.html</p>


</main>

{% endblock %}